export const CHANGE_STYLE_MODE= 'CHANGE_STYLE_MODE'

export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_CAPTCHAURL = 'GET_CAPTCHAURL'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_USERINFO = 'GET_USERINFO'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'
export const ADD_COMMENT_NUMBER = 'ADD_COMMENT_NUMBER'

export const GET_INDEX_IMG = 'GET_INDEX_IMG'
export const GET_INDEX_IMG_REQUEST = 'GET_INDEX_IMG_REQUEST'
export const GET_INDEX_IMG_SUCCESS = 'GET_INDEX_IMG_SUCCESS'
export const GET_INDEX_IMG_FAILURE = 'GET_INDEX_IMG_FAILURE'

export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE'

export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const ARTICLE_DETAIL_REQUEST = 'ARTICLE_DETAIL_REQUEST'
export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS'
export const ARTICLE_DETAIL_FAILURE = 'ARTICLE_DETAIL_FAILURE'

export const COMMENT_LIST = 'COMMENT_LIST'
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAILURE = 'COMMENT_LIST_FAILURE'

export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const TOGGLE_LIKE_REQUEST = 'TOGGLE_LIKE_REQUEST'
export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS'
export const TOGGLE_LIKE_FAILURE = 'TOGGLE_LIKE_FAILURE'
export const TOGGLE_LIKE_EXBUG = 'TOGGLE_LIKE_EXBUG'

export const PRENEXT_ARTICLE = 'PRENEXT_ARTICLE'
export const PRENEXT_ARTICLE_REQUEST = 'PRENEXT_ARTICLE_REQUEST'
export const PRENEXT_ARTICLE_SUCCESS = 'PRENEXT_ARTICLE_SUCCESS'
export const PRENEXT_ARTICLE_FAILURE = 'PRENEXT_ARTICLE_FAILURE'

export const TAG_LIST = 'TAG_LIST'
export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST'
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS'
export const TAG_LIST_FAILURE = 'TAG_LIST_FAILURE'

export const GET_APPS = 'GET_APPS'
export const GET_APPS_SUCCESS = 'GET_APPS_SUCCESS'
export const GET_APPS_FAILURE = 'GET_APPS_FAILURE'
export const GET_APPS_REQUEST = 'GET_APPS_REQUEST'

export const GET_SNSLOGINS = 'GET_SNSLOGINS'
export const GET_SNSLOGINS_SUCCESS = 'GET_SNSLOGINS_SUCCESS'
export const GET_SNSLOGINS_FAILURE = 'GET_SNSLOGINS_FAILURE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

//admin
export const GET_ADMINCOMMENT = 'GET_ADMINCOMMENT'
export const GET_ADMINCOMMENT_SUCCESS = 'GET_ADMINCOMMENT_SUCCESS'
export const GET_ADMINCOMMENT_FAILURE = 'GET_ADMINCOMMENT_FAILURE'
export const GET_ADMINCOMMENT_REQUEST = 'GET_ADMINCOMMENT_REQUEST'

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE'
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'

export const GET_ADMINTAG = 'GET_ADMINTAG'
export const GET_ADMINTAG_SUCCESS = 'GET_ADMINTAG_SUCCESS'
export const GET_ADMINTAG_FAILURE = 'GET_ADMINTAG_FAILURE'
export const GET_ADMINTAG_REQUEST = 'GET_ADMINTAG_REQUEST'

export const ADD_ADMINTAG = 'ADD_ADMINTAG'
export const ADD_ADMINTAG_SUCCESS = 'ADD_ADMINTAG_SUCCESS'
export const ADD_ADMINTAG_FAILURE = 'ADD_ADMINTAG_FAILURE'
export const ADD_ADMINTAG_REQUEST = 'ADD_ADMINTAG_REQUEST'

export const DELETE_ADMINTAG = 'DELETE_ADMINTAG'
export const DELETE_ADMINTAG_SUCCESS = 'DELETE_ADMINTAG_SUCCESS'
export const DELETE_ADMINTAG_FAILURE = 'DELETE_ADMINTAG_FAILURE'
export const DELETE_ADMINTAG_REQUEST = 'DELETE_ADMINTAG_REQUEST'

export const GET_ADMINUSER = 'GET_ADMINUSER'
export const GET_ADMINUSER_SUCCESS = 'GET_ADMINUSER_SUCCESS'
export const GET_ADMINUSER_FAILURE = 'GET_ADMINUSER_FAILURE'
export const GET_ADMINUSER_REQUEST = 'GET_ADMINUSER_REQUEST'

export const ADD_ADMINUSER = 'ADD_ADMINUSER'
export const ADD_ADMINUSER_SUCCESS = 'ADD_ADMINUSER_SUCCESS'
export const ADD_ADMINUSER_FAILURE = 'ADD_ADMINUSER_FAILURE'
export const ADD_ADMINUSER_REQUEST = 'ADD_ADMINUSER_REQUEST'

export const DELETE_ADMINUSER = 'DELETE_ADMINUSER'
export const DELETE_ADMINUSER_SUCCESS = 'DELETE_ADMINUSER_SUCCESS'
export const DELETE_ADMINUSER_FAILURE = 'DELETE_ADMINUSER_FAILURE'
export const DELETE_ADMINUSER_REQUEST = 'DELETE_ADMINUSER_REQUEST'